### ISSUE TITLE
Fehler in Contao 4.8.7

### ISSUE THREAD

**Issue by frontendschlampe** [hofff/contao-layoutusage#1]
Seit Contao 4.8.7 funktioniert die Erweiterung nicht mehr. Wenn man auf die Layouts geht kommt

`Warning: sprintf(): Too few arguments`

In Contao 4.8.6 hat es noch problemlos funktioniert. Scheinbar wurde da was in Contao geändert. Müssten wir mal irgendwie prüfen, ob wir den Fehler finden.

**Comment by dmolineus** [comment]
Behoben durch e33b46981f0c364b4ee85891bf10ba54b4d77eb9
