### ISSUE TITLE
Nur bis PHP 7.1

### ISSUE THREAD

**Issue by Anke** [hofff/contao-layoutusage#2]
Hallo,

das war so ein dankbares Helferlein! Ich würde mich freuen, wenn es, sofern es die Zeit erlaubt, für PHP 8+ fit gemacht würde.

VG
Anke

**Comment by frontendschlampe** [comment]
Wir haben es auf dem Plan und würden uns im Rahmen eines Projektes die nächsten Wochen darum bemühen.

**Comment by dmolineus** [comment]
Version 3.0.0 bietet nun Contao 5 und PHP 8 Support
