### ISSUE TITLE
Läuft mit PHP 8.1 bitte Bedingung so hinterlegen

### ISSUE THREAD

**Issue by himbeerrot** [hofff/contao-layoutusage#3]
Hallo,
layoutusage läuft mit PHP 8.1
Könnt ihr bitte die Bedingung so hinterlegen, dass der Contao-Manager diese Erweiterung akzeptiert, wenn der Webspace mit PHP 8.1 läuft?
Das wäre fein!
Danke und Gruß
Holger

**Comment by Schmidty2** [comment]
+1

Danke :-)

**Comment by frontendschlampe** [comment]
Ich habe mal die PHP Version im Master angepasst. Könnt also die Erweiterung als `dev-master` installieren. Wenn es keinerlei Probleme gibt, werden wir eine neue Version taggen.

**Comment by Schmidty2** [comment]
Danke - läuft in drei Installationen bisher ohne Probleme unter PHP 8.1.7 bei All-Inkl

**Comment by Metis77** [comment]
`dev-master` läuft auch bei mir wunderbar mit PHP 8.1.
@frontendschlampe  Gerne per Tag veröffentlichen

**Comment by dmolineus** [comment]
Version 3.0.0 bietet nun Contao 5 und PHP 8 Support
